name: Deploy to EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy files to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC20m9Z2rew+dlhmywG89UKWLlV0I+J1X59wm+xiy0XOz4TVQfgPD+7zZw+Zf/pZkMs7v6sy9pRGNNvi6LsqI8Dw1byRrEoHvGwT1a2rSAMoyM7gu5A+xzjp4UcGBNlKwaqAuSFqd50TtigkdECCdG7Ejbi6IC/v8k9D5Za+DsGiznwwjRC7kiSdKxBc5E9RufGiglsRKJknhFwlJywnf0tZ0SxePLJ4+Gr46BnTre27E+8/yFr0XkU5I8uU0LM2f8/tGSC5B9YapiSs7OfsYUB4D7USQBAgsC/1Jeboxh+KWD+8LlSM+mwMz3Fk+PpH0w6hD7b6S2a5vO6CWHNumk9B+y2VLHittfYnTyyIuh8HF7Y+zb1vAAK24NOO21eiwLb8p4RKVLaC74dvpcYu85sTvZzHPfXDup8OB2eo4JwGvteNKf0VAsYKSxmsQvzp41vUCVc0CTYIzMNYUkrhzGmJiAdS3UtED15nz2TyOmLraFBkgGctBusy+swWd/ltR92JFBcjS98vqSlikw/S2DwmZ9u7pcz95kdAUQH8CPECXWW59pTxUIreirJlJ4ewELBg+8XnJ2LwHh841KiE0tzpwQHzJcFowEBcAfC5isIbNh0yh/MyA4aCT/EcnWHvTfz9sTmKG4EL/eas0rWptma9rT78pxZW05V1pSpqoD53Q== bp2228@nau.edu
          SOURCE: "."

      - name: Setup and configure Apache2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system packages
            sudo apt-get update -y
            
            # Install Apache2 if not already installed
            sudo apt-get install -y apache2
            
            # Start and enable Apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Navigate to the deployment directory
            cd ${{ secrets.TARGET_DIR }}
            
            # Copy HTML files to Apache web root
            sudo cp *.html /var/www/html/
            
            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
            
            # Configure Apache to serve the main HTML file as index
            if [ -f "/var/www/html/assignment1.html" ]; then
              sudo cp /var/www/html/assignment1.html /var/www/html/index.html
            fi
            
            # Restart Apache to apply changes
            sudo systemctl restart apache2
            
            # Check Apache status
            sudo systemctl status apache2 --no-pager
            
            echo "Deployment completed successfully!"
