          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system packages
            sudo apt-get update -y
            
            # Install Apache2 if not already installed
            sudo apt-get install -y apache2
            
            # Start and enable Apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Navigate to the deployment directory
            cd ${{ secrets.TARGET_DIR }}
            
            # Copy HTML files to Apache web root
            sudo cp *.html /var/www/html/
            
            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
            
            # Configure Apache to serve the main HTML file as index
            if [ -f "/var/www/html/assignment1.html" ]; then
              sudo cp /var/www/html/assignment1.html /var/www/html/index.html
            fi
            
            # Restart Apache to apply changes
            sudo systemctl restart apache2
            
            # Check Apache status
            sudo systemctl status apache2 --no-pager
            
            echo "Deployment completed successfully!"
