name: Deploy to EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Debug - Check secrets configuration
        run: |
          echo "=========================================="
          echo "🔍 CHECKING GITHUB SECRETS"
          echo "=========================================="
          
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "❌ EC2_SSH_KEY secret is NOT SET"
          else
            echo "✅ EC2_SSH_KEY secret is configured (length: ${#EC2_SSH_KEY})"
            echo "First 50 chars: $(echo '${{ secrets.EC2_SSH_KEY }}' | head -c 50)..."
          fi
          
          if [ -z "${{ secrets.HOST_DNS }}" ]; then
            echo "❌ HOST_DNS secret is NOT SET"
          else
            echo "✅ HOST_DNS secret is configured: ${{ secrets.HOST_DNS }}"
          fi
          
          if [ -z "${{ secrets.USERNAME }}" ]; then
            echo "❌ USERNAME secret is NOT SET"
          else
            echo "✅ USERNAME secret is configured: ${{ secrets.USERNAME }}"
          fi
          
          if [ -z "${{ secrets.TARGET_DIR }}" ]; then
            echo "❌ TARGET_DIR secret is NOT SET"
          else
            echo "✅ TARGET_DIR secret is configured: ${{ secrets.TARGET_DIR }}"
          fi
          
          echo "=========================================="

      - name: Test SSH Key Format
        run: |
          echo "=========================================="
          echo "🔑 TESTING SSH KEY FORMAT"
          echo "=========================================="
          
          # Create a temporary file with the SSH key
          echo '${{ secrets.EC2_SSH_KEY }}' > /tmp/test_key
          chmod 600 /tmp/test_key
          
          # Test if the key is valid
          if ssh-keygen -l -f /tmp/test_key 2>/dev/null; then
            echo "✅ SSH key format is valid"
          else
            echo "❌ SSH key format is INVALID"
            echo "Key content preview:"
            head -c 100 /tmp/test_key
            echo "..."
          fi
          
          # Clean up
          rm -f /tmp/test_key
          echo "=========================================="

      - name: Deploy files to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SOURCE: "."

      - name: Setup and configure Apache2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system packages
            sudo apt-get update -y
            
            # Install Apache2 if not already installed
            sudo apt-get install -y apache2
            
            # Start and enable Apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            
            # Navigate to the deployment directory
            cd ${{ secrets.TARGET_DIR }}
            
            # Copy HTML files to Apache web root
            sudo cp *.html /var/www/html/
            
            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/html/
            sudo chmod -R 755 /var/www/html/
            
            # Configure Apache to serve the main HTML file as index
            if [ -f "/var/www/html/assignment1.html" ]; then
              sudo cp /var/www/html/assignment1.html /var/www/html/index.html
            fi
            
            # Restart Apache to apply changes
            sudo systemctl restart apache2
            
            # Check Apache status
            sudo systemctl status apache2 --no-pager
            
            echo "Deployment completed successfully!"
